services:
  db:
    image: postgres:13-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: tuiter
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres1234
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432